name: meeting_note_summarizer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Audio processing
  record: ^5.0.4
  permission_handler: ^11.0.1
  # Database and storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  # State management
  provider: ^6.1.1
  # Utilities
  uuid: ^4.1.0
  intl: ^0.18.1
  # AI/ML integration
  ffi: ^2.1.0
  # HTTP client for model downloads
  http: ^1.1.0
  # Archive extraction for model files
  archive: ^3.4.10
  # Isolates for background processing
  compute: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Testing utilities
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
