name: meeting_note_summarizer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Audio processing
  record: ^5.0.4
  permission_handler: ^11.0.1
  # Speech recognition
  speech_to_text: ^6.6.0
  # Database and storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  # State management
  provider: ^6.1.1
  # Utilities
  uuid: ^3.0.7
  intl: ^0.18.1
  # AI/ML integration
  ffi: ^2.1.0
  # HTTP client for model downloads
  http: ^1.1.0
  # Archive extraction for model files
  archive: ^3.4.10
  # Isolates for background processing
  compute: ^1.0.0
  # Audio format conversion
  wav: ^1.0.0
  # File operations
  file_picker: ^8.0.0+1
  # Platform-specific audio capture
  flutter_sound: ^9.2.13
  # Native audio processing
  audio_session: ^0.1.19
  # JSON serialization
  json_annotation: ^4.8.1
  # Crypto for model verification
  crypto: ^3.0.3
  # Platform detection
  platform: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Development dependencies
  build_runner: ^2.4.7
  # JSON code generation
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Bundle AI models as assets
  assets:
    - assets/models/
    - assets/models/whisper-tiny.bin
    - assets/models/tinyllama-q4.gguf
